version: '3.5'
services:
  node:
    container_name: api_node
    build:
      context: ./
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - db
  db:
    container_name: api_postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./data/pgdata/:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
